### ISSUE TITLE
Panic in hostess ls

### ISSUE THREAD

**Issue by cbednarski** [cbednarski/hostess#14]
The following file results in a panic when run through `hostess ls`.

```
#192.168.0.1 pie.dev.example.com
192.168.0.2 cookie.example.com
::1 hostname.pie hostname.candy cake.example.com
fe:23b3:890e:342e::ef strawberry.pie.example.com
# fe:23b3:890e:342e::ef dev.strawberry.pie.example.com
192.168.1.3 pie.example.com
127.0.1.1 robobrain
# fe:23b3:890e:342e::ef chocolate.cake.example.com chocolate.ru.example.com chocolate.tr.example.com chocolate.cookie.example.com
fe:23b3:890e:342e::ef chocolate.pie.example.com
::1 localhost
127.0.0.1 localhost
192.168.1.1 pie.example.com
192.168.1.1 strawberry.pie.example.com
```

Failure output:

```
~/code/cbednarski.com (master) 1$ HOSTESS_PATH=examplehosts hostess ls
Conflicting hostname entries for na.leagueoflegends.com -> 192.168.1.1 and -> 192.168.1.3
localhost                        -> 127.0.0.1        (On)
robobrain                        -> 127.0.1.1        (On)
na.dev.leagueoflegends.com       -> 192.168.0.1      (Off)
euw.leagueoflegends.com          -> 192.168.0.2      (On)
na.leagueoflegends.com           -> 192.168.1.1      (On)
promo.na.leagueoflegends.com     -> 192.168.1.1      (On)
localhost                        -> ::1              (On)
eune.leagueoflegends.com         -> ::1              (On)
hostname.candy                   -> ::1              (On)
hostname.pie                     -> ::1              (On)
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
panic(0x1ec660, 0xc82000fa30)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
strings.Repeat(0x22c968, 0x1, 0xfffffffffffffffb, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:427 +0x5f
github.com/cbednarski/hostess.StrPadRight(0xc82000b8e0, 0x15, 0x10, 0x0, 0x0)
	/Users/cbednarski/go/src/github.com/cbednarski/hostess/commands.go:79 +0x4e
github.com/cbednarski/hostess.Ls(0xc82009c3c0)
	/Users/cbednarski/go/src/github.com/cbednarski/hostess/commands.go:209 +0x19c
github.com/codegangsta/cli.Command.Run(0x22f0c8, 0x4, 0x0, 0x0, 0xc82000ea80, 0x1, 0x1, 0x261e00, 0x1e, 0x0, ...)
	/Users/cbednarski/go/src/github.com/codegangsta/cli/command.go:179 +0x1399
github.com/codegangsta/cli.(*App).Run(0xc8200906e0, 0xc82000a220, 0x2, 0x2, 0x0, 0x0)
	/Users/cbednarski/go/src/github.com/codegangsta/cli/app.go:196 +0x137c
main.main()
	/Users/cbednarski/go/src/github.com/cbednarski/hostess/cmd/hostess/hostess.go:117 +0xa6c
```

The problem persists after running `hostess fix`, even though `hostess fix` succeeds.

**Comment by cbednarski** [comment]
Fixed in https://github.com/cbednarski/hostess/commit/35413097c799bc32955e3aad1f9317b2b93621e4
