### ISSUE TITLE
Binary for Mac x64 errors when run with no arguments

### ISSUE THREAD

**Issue by jmgilman** [cbednarski/hostess#43]
When downloading the latest (0.5.2) binary for MacOS x64 and running the binary with no arguments gives the following error:

```
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
main.wrappedMain(0xc000012200, 0x1, 0x1, 0x0, 0xc000100058)
	/Users/cbednarski/code/hostess/main.go:78 +0xd5b
main.main()
	/Users/cbednarski/code/hostess/main.go:147 +0x45
```

I'm not sure what source the binary is running, and if its the latest, but I would imagine the issue has something to do with main.go:83 causing an index out of bounds error. If the reference to main.go:78 is accurate, then that's a strange error to me, as I'm not sure how the slice could be out of bounds when the length is greater than 1.

More interesting is the fact that it only happens with the release binary. I can clone and build/run the binary locally and it does not reproduce this error. It only occurs when running the binary retrieved off the release page. Not sure what tool you are using for generating releases, but it appears to be doing something odd with the Mac binary.

**Comment by cbednarski** [comment]
Thanks for the report! I see that this is fixed on master but it seems I did not cut a release. I will need to release 0.5.3. If you build from master it should be resolved. Apologies for the inconvenience!

**Comment by jmgilman** [comment]
Ah, that makes sense with what I saw. Glad I could be of help and thanks for this awesome tool!

**Comment by fhuitelec** [comment]
Hi :wave: Is the `0.5.3` release still planned?

**Comment by jsardev** [comment]
Bump 😄
